import Navbar from "@/components/Shared/Navbar";
import "@/app/globals.css";
import Footer from "@/components/Shared/Footer";

export const metadata = {
  title: "Next.js Nested",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <>
      <Navbar />
      <div className="min-h-screen text-4xl">{children}</div>
      <Footer />
    </>
  );
}
