/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.JDBC.JDBCManager;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.event.MouseInputListener;

/**
 *
 * @author FURIOUS
 */
public class PlayerRegistrationForm extends AbstractFrame {

    protected static JFrame frame = null;
    static Integer[] designers = null;
    static Integer[] catagories = null;
    static Integer[] games = null;
    static JCheckBox[] chkbox = null;
    static ArrayList<String> tempSelectedDesigners = new ArrayList<>();
    static ArrayList<String> tempSelectedCatagory = new ArrayList<>();
    static ArrayList<String> tempSelectedGames = new ArrayList<>();
//    static String playerName;
//    static String playerEmail;
//    static String location;
//    static String fromTime;
//    static String toTime;
//    static String optimalPlayer;
//    static String password;

    /**
     * Creates new form RegisterPlayer
     */
    public PlayerRegistrationForm() {
        initComponents();
        frame = this;
        final int size = view.Hours.getHourList().length;

        for (int x = 0; x < size; x++) {
            cmbFromTime.addItem(view.Hours.getHourList()[x]);
            cmbToTime.addItem(view.Hours.getHourList()[x]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblShowNameText = new javax.swing.JLabel();
        lblShowAddressText = new javax.swing.JLabel();
        lblShowLocationText = new javax.swing.JLabel();
        lblShowAvailabilityText = new javax.swing.JLabel();
        lblShowOptimalNumberText = new javax.swing.JLabel();
        txtPlayerName = new javax.swing.JTextField();
        txtPlayerEmail = new javax.swing.JTextField();
        cmbFromTime = new javax.swing.JComboBox<>();
        cmbOptimalPlayer = new javax.swing.JComboBox<>();
        btnNext = new javax.swing.JButton();
        lblShowPasswordText = new javax.swing.JLabel();
        psw = new javax.swing.JPasswordField();
        lblToText = new javax.swing.JLabel();
        cmbToTime = new javax.swing.JComboBox<>();
        txtLocation = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 255));

        lblShowNameText.setText("Name");

        lblShowAddressText.setText("Email address");

        lblShowLocationText.setText("Location");

        lblShowAvailabilityText.setText("Available timeslot");

        lblShowOptimalNumberText.setText("Optimal numbers");

        cmbOptimalPlayer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "True", "False" }));

        btnNext.setBackground(new java.awt.Color(51, 102, 255));
        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        lblShowPasswordText.setText("Password");

        lblToText.setText("to");

        btnBack.setBackground(new java.awt.Color(255, 51, 51));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblShowAddressText)
                        .addComponent(lblShowNameText)
                        .addComponent(lblShowLocationText)
                        .addComponent(lblShowOptimalNumberText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblShowPasswordText)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblShowAvailabilityText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPlayerName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPlayerEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbOptimalPlayer, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(psw, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cmbFromTime, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblToText)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cmbToTime, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnNext, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblShowNameText))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlayerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblShowAddressText))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblShowLocationText)
                    .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblShowAvailabilityText, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbFromTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblToText)
                    .addComponent(cmbToTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblShowOptimalNumberText)
                    .addComponent(cmbOptimalPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblShowPasswordText)
                    .addComponent(psw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext)
                    .addComponent(btnBack))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        String playerName = PlayerRegistrationForm.txtPlayerName.getText();
        String playerEmail = PlayerRegistrationForm.txtPlayerEmail.getText();
        String location = PlayerRegistrationForm.txtLocation.getText();
        String fromTime = PlayerRegistrationForm.cmbFromTime.getSelectedItem().toString();
        String toTime = PlayerRegistrationForm.cmbToTime.getSelectedItem().toString();
        String optimalPlayer = PlayerRegistrationForm.cmbOptimalPlayer.getSelectedItem().toString();
        String password = PlayerRegistrationForm.psw.getText();
        if (playerEmail.isEmpty() || playerName.isEmpty() || location.isEmpty() || fromTime.isEmpty() || toTime.isEmpty() || optimalPlayer.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(frame, "Some fields are missing.");
        } else {
            SelectCatagoryPlayerRegistrationForm scprf = new SelectCatagoryPlayerRegistrationForm();
            scprf.setVisible(true);
            frame.setVisible(false);
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        PlayerPanel ps = new PlayerPanel();
        ps.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNext;
    protected static javax.swing.JComboBox<String> cmbFromTime;
    protected static javax.swing.JComboBox<String> cmbOptimalPlayer;
    protected static javax.swing.JComboBox<String> cmbToTime;
    private javax.swing.JLabel lblShowAddressText;
    private javax.swing.JLabel lblShowAvailabilityText;
    private javax.swing.JLabel lblShowLocationText;
    private javax.swing.JLabel lblShowNameText;
    private javax.swing.JLabel lblShowOptimalNumberText;
    private javax.swing.JLabel lblShowPasswordText;
    private javax.swing.JLabel lblToText;
    protected static javax.swing.JPasswordField psw;
    protected static javax.swing.JTextField txtLocation;
    protected static javax.swing.JTextField txtPlayerEmail;
    protected static javax.swing.JTextField txtPlayerName;
    // End of variables declaration//GEN-END:variables
}
