/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.JDBC.JDBCManager;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import static view.PlayerRegistrationForm.catagories;
import static view.PlayerRegistrationForm.chkbox;
import static view.PlayerRegistrationForm.tempSelectedCatagory;

/**
 *
 * @author FURIOUS
 */
public class SelectCatagoryPlayerRegistrationForm extends AbstractFrame {
    JPanel pnlCheckbox = new JPanel();
    /**
     * Creates new form SelectGamePlayerRegistrationForm
     */
    public SelectCatagoryPlayerRegistrationForm() {
        initComponents();

        JFrame frame = this;
        JDBCManager manager = new JDBCManager();
        manager.initSqliteConnection("bg.db");
        String sql = "SELECT gc.catagoryId, gc.catagoryName FROM GameCatagory gc;";
        
        //Copied code
        ArrayList<HashMap<String, String>> al = manager.getQueryData(sql);
        int size = al.size();
        catagories = new Integer[size];
        pnlCheckbox.setLayout(new GridLayout(size, 1, 0, 2));
        JButton btnAdd = this.btnNext;
        chkbox = new JCheckBox[size];
        for (int i = 0; i < size; i++) {
            chkbox[i] = new JCheckBox();
            chkbox[i].setText(al.get(i).get("catagoryName"));
            pnlCheckbox.add(chkbox[i]);
            for (int j = 0; j < tempSelectedCatagory.size(); j++) {
                if (chkbox[i].getText().equals(tempSelectedCatagory.get(j))) {
                    chkbox[i].setSelected(true);
                    break;
                }
            }
        }

        frame.setDefaultCloseOperation(2);
        btnAdd.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                tempSelectedCatagory.clear();
                int size = chkbox.length;
                for (int i = 0, j = 0; i < size; i++) {
                    if (chkbox[i].isSelected() == true) {
                        tempSelectedCatagory.add(chkbox[i].getText());
                        catagories[j++] = new Integer(al.get(i).get("catagoryId"));
                    }
                }
                frame.dispose();
                SelectDesignerPlayerRegistrationForm sdprf = new SelectDesignerPlayerRegistrationForm();
                sdprf.setVisible(true);
            }
        });
        
        btnBack.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                frame.dispose();
                new PlayerRegistrationForm().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scpn = new javax.swing.JScrollPane(pnlCheckbox);
        btnNext = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 255));

        btnNext.setBackground(new java.awt.Color(51, 102, 255));
        btnNext.setText("Next");

        btnBack.setBackground(new java.awt.Color(255, 51, 51));
        btnBack.setText("Back");

        jLabel1.setText("Please select at least one game catagory");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scpn)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNext))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 122, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scpn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext)
                    .addComponent(btnBack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane scpn;
    // End of variables declaration//GEN-END:variables
}
