/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.JDBC.JDBCManager;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author FURIOUS
 */
public class AddNewGame extends Frame {

    /**
     * Creates new form AddNewGame
     */
    public AddNewGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtGameName = new javax.swing.JTextField();
        txtGameDesigner = new javax.swing.JTextField();
        txtMinPlayer = new javax.swing.JTextField();
        txtMaxPlayer = new javax.swing.JTextField();
        txtGameCatagory = new javax.swing.JTextField();
        btnAddGame = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Game name");

        jLabel2.setText("Game designer");

        jLabel3.setText("Minimum player");

        jLabel4.setText("Maximum player");

        jLabel5.setText("Game catagory");

        txtMinPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinPlayerActionPerformed(evt);
            }
        });

        btnAddGame.setText("Add game");
        btnAddGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddGameActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtGameName)
                        .addComponent(txtGameDesigner)
                        .addComponent(txtMinPlayer)
                        .addComponent(txtMaxPlayer)
                        .addComponent(txtGameCatagory, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                    .addComponent(btnAddGame, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtGameName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtGameDesigner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMinPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMaxPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtGameCatagory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddGame)
                    .addComponent(jButton1))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMinPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinPlayerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinPlayerActionPerformed

    private void btnAddGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGameActionPerformed
        // TODO add your handling code here:
        try{
        String gameName = txtGameName.getText();
        String gameDesigner = txtGameDesigner.getText();
        String maxPlayer = txtMaxPlayer.getText();
        String minPlayer = txtMinPlayer.getText();
        String gameCatagory = txtGameCatagory.getText();

        Integer designerId = null;
        Integer catagoryId = null;
        JDBCManager manager = new JDBCManager();
        manager.initSqliteConnection("bg.db");
        String sql = "SELECT gd.designerId, gd.designerName FROM GameDesigner gd WHERE gd.designerName = ?;";
        ArrayList<HashMap<String, String>> al = manager.getQueryData(sql, gameDesigner);
        if (al.size() == 0) {
            sql = " INSERT INTO GameDesigner(designerName) VALUES (?);";
            manager.insertData(sql, gameDesigner);
            sql = "SELECT gd.designerId FROM GameDesigner gd WHERE gd.designerName = ?;";
            al = manager.getQueryData(sql, gameDesigner);
            designerId = Integer.parseInt(al.get(0).get("designerId"));
            System.err.println("designerId Id @Line-152 "+designerId);
        } else {
            System.out.println("designerId Id @Line-154 "+Integer.parseInt(al.get(0).get("designerId")));
            designerId = Integer.parseInt(al.get(0).get("designerId"));
            System.err.println("designerId Id @Line-155 "+designerId);
        }
        sql = "SELECT gc.catagoryId, gc.catagoryName FROM GameCatagory gc WHERE gc.catagoryName = ?;";
        al = manager.getQueryData(sql, gameCatagory);
        if (al.size() == 0) {
            sql = "INSERT INTO GameCatagory(catagoryName) VALUES(?);";
            manager.insertData(sql, gameCatagory);
            sql = "SELECT gc.catagoryId FROM GameCatagory gc WHERE gc.catagoryName = ?;";
            al = manager.getQueryData(sql, gameCatagory);
            catagoryId = Integer.parseInt(al.get(0).get("catagoryId"));
            System.err.println("Catagory Id @Line-165 "+catagoryId);
        } else {
            catagoryId = Integer.parseInt(al.get(0).get("catagoryId"));
            System.err.println("Catagory Id @Line-169 "+catagoryId);
        }
        sql = "SELECT g.gameName FROM game g WHERE g.gameName = ?;";
        if (manager.contains(sql, gameName)==true) {
            JOptionPane.showMessageDialog(null, "This game already exists.");
        } else {
            sql = "INSERT INTO game(gameName, maxPlayer, minPlayer, optimalPlayer, gameCatagory, gameDesigner) VALUES(?,?,?,?,?,?);";
            boolean flag = manager.insertData(sql, gameName, Integer.parseInt(maxPlayer), Integer.parseInt(minPlayer), Integer.parseInt("4"), catagoryId, designerId);
            if (flag == true) {
                JOptionPane.showMessageDialog(this, "All data was inserted successfully");
            }
        }
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(this, "Invalid data");
        }
        
    }//GEN-LAST:event_btnAddGameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        BoardGameManagementPanel s = new BoardGameManagementPanel();
        s.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddGame;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtGameCatagory;
    private javax.swing.JTextField txtGameDesigner;
    private javax.swing.JTextField txtGameName;
    private javax.swing.JTextField txtMaxPlayer;
    private javax.swing.JTextField txtMinPlayer;
    // End of variables declaration//GEN-END:variables
}
