import "@/app/globals.css";

export const metadata = {
  title: "Next.js product",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <>
      <h1>Header product</h1>
      <div className="min-h-screen text-4xl">{children}</div>
      <h1>Footer product</h1>
    </>
  );
}
